query currentBulkOperation{
    currentBulkOperation(type: %(job_type)s) {
        id
        status
        errorCode
        createdAt
        completedAt
        objectCount
        fileSize
        url
        partialDataUrl
    }
}
