mutation bulkOperationRunMutation{
  bulkOperationRunMutation(
    mutation: """%(mutation_query)s""",
    stagedUploadPath: "%(staged_upload_path)s"
  )
  {
    bulkOperation {
      id
      url
      status
    }
    userErrors {
      message
      field
    }
  }
}
