mutation stagedUploadsCreate{
  stagedUploadsCreate(
    input: {
      resource: BULK_MUTATION_VARIABLES
      filename: "%(filename)s"
      mimeType: "text/jsonl"
      httpMethod: POST
    }
  ) {
    userErrors {
      message
      field
    }
    stagedTargets {
      url
      resourceUrl
      parameters {
        name
        value
      }
    }
  }
}
