mutation bulkOperationRunQuery{
  bulkOperationRunQuery(
    query: """
      %(sub_query)s
    """
  ) {
    bulkOperation {
      id
      status
    }
    userErrors {
      field
      message
    }
  }
}
